### ISSUE TITLE
h2o-release s3 bucket files gone

### ISSUE THREAD

**Issue by sshenoy-mdsol** [h2oai/h2o-3#16477]
**H2O version, Operating System and Environment**
3.44.0
Ubuntu 22.04.5 LTS-R version 4.1.3

**Actual behavior**
h2o R package fails to install due to missing s3 file: https://s3.amazonaws.com/h2o-release/h2o/rel-3.44.0/3/Rjar/h2o.jar

**Expected behavior**
Ability to install h2o R package

Error: Error: Error installing package 'h2o':
===============================

* installing *source* package ‘h2o’ ...
** package ‘h2o’ successfully unpacked and MD5 sums checked
** using staged installation
** R
** demo
** inst
** byte-compile and prepare package for lazy loading
Performing one-time download of h2o.jar from
     https://s3.amazonaws.com/h2o-release/h2o/rel-3.44.0/3/Rjar/h2o.jar 
(This could take a few minutes, please be patient...)
Warning in download.file(url = h2o_url, destfile = temp_file, mode = "wb",  :
  cannot open URL 'https://s3.amazonaws.com/h2o-release/h2o/rel-3.44.0/3/Rjar/h2o.jar': HTTP status was '404 Not Found'
Error in download.file(url = h2o_url, destfile = temp_file, mode = "wb",  : 
  cannot open URL 'https://s3.amazonaws.com/h2o-release/h2o/rel-3.44.0/3/Rjar/h2o.jar'
Error: Error: unable to load R code in package ‘h2o’
Execution halted
ERROR: lazy loading failed for package ‘h2o’

**Comment by sshenoy-mdsol** [comment]
I assume this goes beyond this specific version of h2o since all links to the download page on https://docs.h2o.ai/h2o/latest-stable/h2o-docs/downloading.html are broken

https://h2o-release.s3.amazonaws.com/h2o/latest_stable.html

**Comment by RoelVerbelen** [comment]
Facing same issue.

**Comment by moravveji** [comment]
I hit the same problem while installing the [R-bundle-CRAN](https://github.com/easybuilders/easybuild-easyconfigs/tree/develop/easybuild/easyconfigs/r/R-bundle-CRAN) module on our cluster, using EasyBuild. My remedy was to update the EasyConfig file for pulling the `h2o` source to the following block, to make sure the source bundle is directly pulled from CRAN:
```
    ('h2o', '3.44.0.3', {
        'source_urls': ['https://cran.r-project.org/src/contrib/'],
        'sources': ['%(name)s_%(version)s.tar.gz'],
        'checksums': ['61a85f6c2f15e8e96839f8a4fd3a45eaa6bca90517bb20a4dd36e951d6fd0c82'],
    }),
```
Rebuilding now ... will check in few hours how far I get ;-)

**Comment by tomasfryda** [comment]
Sorry for the inconvenience. There is some internal migration in h2o. It should work again within couple days. 

Until that you should be able to use the following:
```R
> install.packages("h2o", type="source", repos="https://s3.amazonaws.com/h2o-release-migratedv2/h2o/rel-3.44.0/3/R")
```

For other languages than R, see https://s3.amazonaws.com/h2o-release-migratedv2/h2o/rel-3.44.0/3/index.html

**Comment by itsmunishbhardwaj** [comment]
TL;DR internal aws migration is causing this issue. Its resolved now. Can you please try again? @sshenoy-mdsol 

https://h2oai.slack.com/archives/CT1BQCRV5/p1736742720346759?thread_ts=1733834158.624249&cid=CT1BQCRV5

**Comment by tomasfryda** [comment]
@itsmunishbhardwaj I tried it just now and it's still an issue.

You can reproduce it by running `install.packages("h2o", type="source")` in R.

```R
> install.packages("h2o", type="source")
Installing package into ‘/Users/tomasfryda/Library/R/x86_64/4.4/library’
(as ‘lib’ is unspecified)
trying URL 'https://cloud.r-project.org/src/contrib/h2o_3.44.0.3.tar.gz'
Content type 'application/x-gzip' length 665867 bytes (650 KB)
==================================================
downloaded 650 KB

* installing *source* package ‘h2o’ ...
** package ‘h2o’ successfully unpacked and MD5 sums checked
** using staged installation
** R
** demo
** inst
** byte-compile and prepare package for lazy loading
Performing one-time download of h2o.jar from
     https://s3.amazonaws.com/h2o-release/h2o/rel-3.44.0/3/Rjar/h2o.jar
(This could take a few minutes, please be patient...)
Warning in download.file(url = h2o_url, destfile = temp_file, mode = "wb",  :
  cannot open URL 'https://s3.amazonaws.com/h2o-release/h2o/rel-3.44.0/3/Rjar/h2o.jar': HTTP status was '404 Not Found'
Error in download.file(url = h2o_url, destfile = temp_file, mode = "wb",  :
  cannot open URL 'https://s3.amazonaws.com/h2o-release/h2o/rel-3.44.0/3/Rjar/h2o.jar'
Error: unable to load R code in package ‘h2o’
Execution halted
ERROR: lazy loading failed for package ‘h2o’
* removing ‘/Users/tomasfryda/Library/R/x86_64/4.4/library/h2o’
* restoring previous ‘/Users/tomasfryda/Library/R/x86_64/4.4/library/h2o’
Warning in install.packages("h2o", type = "source") :
  installation of package ‘h2o’ had non-zero exit status

The downloaded source packages are in
	‘/private/var/folders/49/kh67vvnj633ftt08t8zfwsvh0000gn/T/RtmpegDIaa/downloaded_packages’
```

**Comment by stamenminkov** [comment]
Same issue. Hope it's solved quickly!

**Comment by sshenoy-mdsol** [comment]
Since the s3 bucket files are still unavailable I used the following workaround:
1. Find the h2o.jar file from an existing installation, e.g.
```
> h2o:::.h2o.downloadJar()
/home/XXX/.cache/R/renv/library/XXX-9d0219ea/R-4.1/x86_64-pc-linux-gnu/h2o/java/h2o.jar
```
2. Wherever you are installing R/h2o, set the env variable `H2O_JAR_PATH` to point to this file. If you are building a docker image you will need to `COPY` the file, e.g.
```
COPY h2o.jar /opt/ml/h2o.jar
ENV H2O_JAR_PATH=/opt/ml/h2o.jar
```
3. Proceed with R package installation

**Comment by tomasfryda** [comment]
@sshenoy-mdsol Thank you for mentioning the `H2O_JAR_PATH`. You can provide the url as the path and it should work as well (just mentioning it since it might be easier to export environment variable in e.g. Dockerfiles when you don't want to add `wget`/`curl` as additional packages.)

```R
> Sys.setenv(H2O_JAR_PATH="https://s3.amazonaws.com/h2o-release-migratedv2/h2o/rel-3.44.0/3/Rjar/h2o.jar")
> install.packages("h2o", type="source")
```

**Comment by tomasfryda** [comment]
It should work again now.

**Comment by owenprough-sift** [comment]
> It should work again now.

It's working again for me. Thanks.
